apiVersion: v1
kind: Service
metadata:
    name: apigateway
    labels:
      name: apigateway
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
    selector:
        name: apigateway
---
apiVersion: v1
kind: Service
metadata:
  name: catalogapi
  labels:
    name: catalogapi
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    name: catalogapi  
---
apiVersion: v1
kind: Service
metadata:
  name: searchapi
  labels:
    name: searchapi
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    name: searchapi
---
apiVersion: v1
kind: Service
metadata:
  name: searchbackgroundtasks
  labels:
    name: searchbackgroundtasks
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    name: searchbackgroundtasks
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    name: rabbitmq
spec:
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
  type: LoadBalancer
  selector:
    name: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: sqldata
  labels:
    name: sqldata
spec:
  ports:
    - port: 1433
      targetPort: 1433
      protocol: TCP
  type: LoadBalancer
  selector:
    name: sqldata
    